### ISSUE TITLE
Unable to get spec description

### ISSUE THREAD

**Issue by bharathp** [sindresorhus/trayballoon#4]
Hi @sindresorhus ,
I'm using this npm since long back successfully with Jasmine v1. Recently I've upgraded to Jasmine v2 and now, I'm unable to get the spec description as **text of my traybaloon**  since there is a limitation in Jasmine v2.
Do you have any solution which overcomes this problem.

Thanks in advance.

**Comment by sindresorhus** [comment]
I don't see how that's related to this module.

**Comment by bharathp** [comment]
@sindresorhus 
I didn't mean that it is an issue related to this module, but just want to confirm whether you have any work around for this.
